name = "airplane-hijacking-websocket-v2"
main = "websocket.js"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [
  { name = "WEBSOCKET_DURABLE_OBJECT", class_name = "WebSocketDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketDurableObject"] 